version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: memo_app
    ports:
      - 8080:80
    command: >
      sh -c "php artisan serve --host=0.0.0.0 --port=80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306

  db:
    image: mysql:5.7
    container_name: mysql_db_memo
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
